apikeys:
  extends:
    file: docker-compose.yml
    service: apikeys
  ulimits:
    nofile:
        soft: 20000
        hard: 40000
    memlock:
        soft: 68719476736
        hard: 68719476736
data_api:
  build: ./data_collection
  container_name: "data_api"
  ports:
    - "4242:4242"
