apikeys:
  build: ./api_keys
  ports:
    - "4343:4343"
  external_links:
    - mongo
data_api:
  build: ./data_collection
  ports:
    - "4242:4242"
  links:
    - apikeys
  external_links:
    - mongo
