version: "2"

networks:
    proton:
                
services:
    apikeys:
      build: ./api_keys
      networks:
        - proton
      container_name: "apikeys"
      ports:
        - "4343:4343"
        - "4344:4344"
    data_api:
      build: ./data_collection
      container_name: "data_api"
      networks:
        - proton
      volumes:
        - "/tmp/"
      ports:
        - "4242:4242"
