apikeys:
  image: dbonev/apikeys
  ports:
    - "4343:4343"
  restart: on-failure
  external_links:
    - mongo
data_api:
  image: dbonev/data_api
  restart: on-failure
  ports:
    - "4242:4242"
  links:
    - apikeys
  external_links:
    - mongo
